---
title: "HW 4"
author: "SDS348 Fall 2019"
date: ""
output:
  html_document: default
  pdf_document: default
---

```{r global_options, include=FALSE}
# DO NOT DELETE THIS CHUNK!
library(knitr)
opts_chunk$set(fig.align="center", fig.height=5, message=FALSE, fig.width=8,tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

## HaoTing Huang hh25923

**This homework is due on Sep 29, 2019 at 11:59pm. Please submit as a pdf file on Canvas.**

*For all questions, include the R commands/functions that you used to find your answer. Answers without supporting code will not receive credit.*

> ### How to submit this assignment
>All homework assignments will be completed using R Markdown. These `.Rmd` files consist of >text/syntax (formatted using Markdown) alongside embedded R code. 
>When you have completed the assignment (by adding R code inside codeblocks and supporting text outside of the codeblocks), create your document as follows:

> - Click the "Knit" button (above) to create an .html file
> - Open the html file in your internet browser to view
> - Go to `File > Print` and print your .html file to a .pdf
> - (or knit to PDF)
> - Upload the .pdf file to Canvas

---

### Question 1:

##### Load the package nycflights13 with library(nycflights13). If you are on running R Studio locally, you must install this package before you can use it! 

##### Run the included code chunk below to save flights and airports to your environment.

```{R}



library(nycflights13)
library(ggplot2)
library(dplyr)

data(flights)
data(airports)
data(airlines)
```

##### Explore the `flights` dataset (e.g., run `glimpse(flights)` read the description of each variable in the help by running `?flights`). How many observations are there (that's how many flights left the three big NYC airports in 2013)!

##### (a) (2 pts) Report the number and proportion of NAs for each variable using summarize_all() and/or mutate_all(). Ideally, you will write your own short function to count NAs by summing a logical and apply it to every column via `summarize_all`, but there are ways that don't involve creating a new function

```{R}
?flights
"There were 336776 flights left the three big NYC airports in 2013."
?lapply
missingProportion <-function(dataframe) lapply(dataframe, function(x)data.frame(nmissing= sum(is.na(x)), n = length(x), missingProportion =sum(is.na(x))/length(x)))

missingProportion(flights)
countNA <- function(x) sum(is.na(x))
flights %>% summarize_all(countNA)
```


##### (b) (2 pts) Remove all rows containing NAs from the dataset (**for the rest of the assignment, we will be using only the complete rows, so overwrite the `flights` dataset or save it as a new object and use it in place of `flights` for the rest of the assignment**). Now, using filter, what airport `dest`ination (three-letter code fine) has the longest `air_time`? 

```{R}
flightsWithoutNA <- flights %>% na.omit()
head(flightsWithoutNA)
flightsWithoutNA %>% filter(air_time == max(air_time)) %>% select(dest)
"HNL has the longest air time"
```


##### (c) (4 pts) Find the mean, standard deviation, count, and standard error of `distance` in each month of each year (average across `day`) for flights from the three different New York airports (`origin`). You will use your sd and count to fine your se ($sd/\sqrt{count}$). Rename your summary variables inside of `summarize()`. 

```{R}

result <-flightsWithoutNA %>% group_by(origin,month,year) %>% summarize(meanDist = mean(distance), Sd = sd(distance), count = n(), Se = Sd/sqrt(count))
result
```

##### (d) (4 pts) Using your results from part (c), make a barplot of mean distance for each month using `ggplot()`. Add manual standard error bars using geom_errorbar() by specifying `aes(x=month, y=your_mean, ymin=your_mean-your_se, ymax=your_mean+your_se)`. Facet (or equivalent) by `origin` and provide labels/ticks on the x-axis for each month. Write a bit about what you see!

```{R}
ggplot(result,aes(month,meanDist)) +
  geom_bar(stat = "identity")+ 
  scale_x_continuous(breaks=1:12)+
  geom_errorbar(aes(x = month, y = meanDist, ymin = meanDist - Se, ymax = meanDist + Se), width = 0.5)+
  facet_wrap(~origin)

#ggplot(result,aes(month,meanDist)) +
  #geom_bar(stat = "summary")+ geom_errorbar(stat = "summary") +  facet_wrap(~origin) +
  #scale_x_continuous(breaks=1:12)
```


*From the barplots above, other than EWR, JFK and LGA both show some level of uniform average throughout the year. JFK has the largest average mean distance in these three barplots. LGA has the smallest mean distance and also the smallest standard error of distance in these three barplots.*

### Question 2 (2 pts)

Let's do some joining! The dataset `airlines` contains the full name of the carrier (examine it!). Join the dataset with the flights dataset so all of the information in `flights` is retained. Using the merged dataset, which carrier (`name`) has the longest average departure delay? Which has the shortest?

```{R}
data(airlines)
mergedAirLines <- left_join(flightsWithoutNA, airlines)
mergedAirLines
mergedAirLines %>% group_by(name) %>% summarise(AverageDeparture = mean(dep_delay,na.rm = T)) %>% arrange(AverageDeparture)
```


*US Airways Inc. has the shortest average departure delay and Frontier Airlines Inc. has the longest departure delay.*


### Question 3 


#### (a) (4 pts) Look at the dataset called `airports`. How many rows does it have? Using `%in%` with `sum()` or `mean()` (or using a join), how many of these airports (variable `faa`) appear in the `flights` dataset as destinations (after removing NA rows from the flights dataset, above)? How many unique destination airports are there in the flights dataset? Which destination airports are in the `flights` dataset but missing from the `airports` dataset? Google those airport codes: what do they have in common?

```{R}
data("airports")
head(airports)
sum(airports$faa%in%flightsWithoutNA$dest )
n_distinct(flightsWithoutNA$dest)
anti_join(flightsWithoutNA, airports, by= c("dest" = "faa")) %>% select(dest) %>% distinct(dest)

```

*Airpots data set has 1458 rows. There are 100 airports in airpots data set appear in the flights data set. There are 104 distinct destination airports in the flights data set. BQN, SJU, STT, and PSE are in the "flights" but not in the "airport: data set. Those missing airport are all located in Virgin islands of the US.*

#### (b) (2 pts) Do a join that results in a dataset that contains only the rows with matches (i.e., none of the airports not appearing in `flights`, none of the destinations not appearing in `airports`). Call `glimpse()` on this final dataset (please don't print the whole thing out).

```{R}
final <- inner_join(flightsWithoutNA, airports, by = c("dest"= "faa"))
glimpse(final)
```

```{R, echo=F}
## DO NOT DELETE THIS BLOCK!
sessionInfo()
Sys.time()
Sys.info()
```